# -*- coding: utf-8 -*-
"""DataAugmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11LuSEMyzLZfbliWY9a018t_p5Xi9-2ZY
"""

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers 
from keras.preprocessing.image import ImageDataGenerator
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

datagen = ImageDataGenerator(rotation_range = 40,
                             shear_range = 0.2,
                             zoom_range = 0.2,
                             horizontal_flip = True,
                             brightness_range = (0.5, 1.5))

X_train = X_train.reshape((1, ) + X_train.shape) 
y_train = y_train.reshape((1, ) + y_train.shape) 

augmented_image = datagen.flow(X_train, y_train, batch_size = 1)

for x, y in augmented_image:
  for i in range(0, 9):
        plt.subplot(330 + 1 + i)
        plt.imshow(y[i].reshape(3, 3, 3))
        plt.show()
        break